<?xml version="1.0" standalone="yes" ?>
<!DOCTYPE document[
        <!ELEMENT document (employee)*>
        <!ELEMENT employee (name, hiredate, projects)>
        <!ELEMENT name (lastname, firstname)>
        <!ELEMENT lastname (#PCDATA)>
        <!ELEMENT firstname (#PCDATA)>
        <!ELEMENT hiredate (#PCDATA)>
        <!ELEMENT projects (project)*>
        <!ELEMENT project (produce,id,price)>
        <!ELEMENT produce (#PCDATA)>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        ]>
<document>
    <employee>
        <name>
            <lastname>Kelly</lastname>
            <firstname>Grace</firstname>
        </name>
        <hiredate>October 15, 2005</hiredate>
        <projects>
            <project>
                <produce>Printer</produce>
                <id>111</id>
                <price>$111.00</price>
            </project>
            <project>
                <produce>Laptop</produce>
                <id>222</id>
                <price>$989.00</price>
            </project>
        </projects>
    </employee>
</document>