=== datyasuo1/LapTrinhC/XMLss2/EventManagement_schema.xsd
<?xml version="1." encoding="UTF-8"?>
<!--
    Document    : ElectionSurvey_schema.xsd
    Author      : vincent
    Description :
        This document define a schema for collecting event details to manage an event.
-->

<xs:schema xmlns:xs="http://www.w3.org/21/XMLSchema"
           targetNamespace="http://www.creatinemanagement.com"
           xmlns="http://www.createivemanagement.com"
           elementFormDefault="qualified">
    <!--definition for simple elements-->
    <xs:element name="Customer" type="xs:string"/>
    <xs:element name="Venue" type="xs:string"/>
    <xs:element name="Date" type="xs:date"/>
    <xs:element name="ContactNumber" type="xs:long"/>
    <xs:element name="Address" type="xs:string"/>
    <xs:element name="TechDelivery" type="xs:string"/>
    <xs:element name="Entertainment" type="xs:string"/>
    <xs:element name="VenueBooking" type="xs:string"/>
    <xs:element name="Theming" type="xs:string"/>

    <!--    definition for simple types-->
    <xs:element name="NoOfGuests">
        <xs:simpleType>
            <xs:restricion base="xs:integer">
                <xs:minInclusive value=""/>
                <xs:maxInclusive value="2"/>
            </xs:restricion>
        </xs:simpleType>
    </xs:element>

    <!--    definition for complex elements    -->
    <xs:element name="Event">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Customer"/>
                <xs:element ref="Venue"/>
                <xs:element ref="Date"/>
                <xs:element ref="NoOfGuests"/>
                <xs:element ref="ContactNumber"/>
                <xs:element ref="Address"/>
            </xs:sequence>
            <xs:attribute name="orderid" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Service">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="TechDelivery"/>
                <xs:element ref="Entertainment"/>
                <xs:element ref="VenueBooking"/>
                <xs:element ref="Theming"/>
            </xs:sequence>
            <xs:attribute name="category" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="EventManager">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Event" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="Service" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== datyasuo1/LapTrinhC/XMLss2/EventManagement.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Document    : ElectionSurvey_schema.xsd
    Author      : vincent
    Description :
        This xml document collects event details for event management.
-->

<EventManager xmlns="http://www.creatinemanagement.com"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.creatinemanagement.com EventManagement_schema.xsd">
    <Event orderid="A556">
        <Customer>TideWaterHouseCoopers</Customer>
        <Venue>Hilton Bermingham Metropole</Venue>
        <Date>2007-04-24</Date>
        <NoOfGuests>500</NoOfGuests>
        <ContactNumber>3453667</ContactNumber>
        <Address>32 High Street, North Midlands</Address>
    </Event>
    <Service category="Annual Conderence">
        <TechDelivery>Multimedia Arrangement</TechDelivery>
        <Entertainment>Media Personality</Entertainment>
        <VenueBooking>Through TravelDesignated Service</VenueBooking>
        <Theming>Emulate Movie Themed Dinner</Theming>
    </Service>
</EventManager>
